repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-toml
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        additional_dependencies:
          - pyproject.toml
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        additional_dependencies:
          - pyproject.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff
